name: Build Icon

on:
  push:
    branches:
      - main
    paths:
      - 'raw/icons/**'
  workflow_dispatch:
    inputs:
      icon_name:
        description: 'Name of the icon to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'

      - name: Install Dependencies
        run: npm install

      - name: Check for New Icons
        run: |
          git diff --name-only HEAD^ HEAD | grep 'raw/icons/' > new_icons.txt
          if [ -s new_icons.txt ]; then
            while read icon; do
              icon_name=$(basename "$icon")
              npm run icons:build-single --icon_name="$icon_name"
            done < new_icons.txt
          fi

      - name: Build Storybook
        run: npm run build

      - name: Deploy Storybook
        run: npx gh-pages -d storybook-static
